paths:
  # Google Colab
  colab: "/content/drive/MyDrive/ML/hog_lbp_Dataset"
  
  # local machine
  local: "data/raw"

data:
  classes: ['city', 'face', 'green', 'office', 'sea']
  img_size: [128, 128]

hog:
  orientations: 9
  pixels_per_cell: [8, 8]
  cells_per_block: [2, 2]

lbp:
  radius: 3
  n_points: 24
  method: 'uniform'

svm:
  C: 1.0
  kernel: 'rbf'
  gamma: 'scale'

training:
  k_folds: 5
  random_state: 42